package com.demo.ws.imp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.demo.ws.HelloWorldws;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-30T20:25:43.811+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "HelloWorld", 
                  wsdlLocation = "http://192.168.0.4/HelloWrold?wsdl",
                  targetNamespace = "http://imp.ws.demo.com/") 
public class HelloWorld extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://imp.ws.demo.com/", "HelloWorld");
    public final static QName HelloWorldPort = new QName("http://imp.ws.demo.com/", "HelloWorldPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.4/HelloWrold?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.4/HelloWrold?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorld(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorld(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorld() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorld(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorld(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorld(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns HelloWorldws
     */
    @WebEndpoint(name = "HelloWorldPort")
    public HelloWorldws getHelloWorldPort() {
        return super.getPort(HelloWorldPort, HelloWorldws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldws
     */
    @WebEndpoint(name = "HelloWorldPort")
    public HelloWorldws getHelloWorldPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldPort, HelloWorldws.class, features);
    }

}
